{{- if not .Values.api.database.existingSecret -}}
{{- if not .Values.api.database.connectionString -}}
{{- fail "api.database.existingSecret or api.database.connectionString is required" -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "act.fullname" . }}-database
  labels:
    {{- include "act.labels" . | nindent 4 }}
type: Opaque
stringData:
  ACT_DATABASE_URL: {{ .Values.api.database.connectionString | quote }}
{{- end }}
